export const Products = [
  {
    id: 1,
    name: "Morocan Super Black Soap",
    image: "../../assets/ProductItems/crown.jpg",
    price: 7520,
    stars: 4,
  },
  {
    id: 2,
    name: "Venus Eye Lashes Collection 4-in-1 Pack",
    image: "../../assets/ProductItems/eyebrow.jpg",
    price: 4999,
    stars: 4,
  },
  {
    id: 3,
    name: "Foot Massage Syetem + Extra face",
    image: "../../assets/ProductItems/hairwasher.jpg",
    price: 5999,
    stars: 3,
  },
  {
    id: 4,
    name: "Whipped Oxygen Moisturizing Cream",
    image: "../../assets/ProductItems/whitedropper.jpg",
    price: 2999,
    stars: 3,
  },
  {
    id: 5,
    name: "Oxygen Plasma Liquids Drops",
    image: "../../assets/ProductItems/dropper.jpg",
    price: 7880,
    stars: 4,
  },
  {
    id: 6,
    name: "Balancing Stray Toner Cream",
    image: "../../assets/ProductItems/spraytoner.jpg",
    price: 5999,
    stars: 4,
  },
  {
    id: 7,
    name: "Allure Cream Conditioner + Shampoo",
    image: "../../assets/ProductItems/haircream.jpg",
    price: 4999,
    stars: 5,
  },
  {
    id: 8,
    name: "Manual hair remover + Extra tooth",
    image: "../../assets/ProductItems/shavingstick.jpg",
    price: 5999,
    stars: 5,
  },
  {
    id: 9,
    name: "Curl Expression Lotion Cream",
    image: "../../assets/ProductItems/curlcream.jpg",
    price: 4999,
    stars: 5,
  },
  {
    id: 10,
    name: "Collagen Super Powder",
    image: "../../assets/ProductItems/collagenpowder.jpg",
    price: 4999,
    stars: 5,
  },
  {
    id: 11,
    name: "Miracle Shampoo + Conditioner",
    image: "../../assets/ProductItems/miracleshampoo.jpg",
    price: 10999,
    stars: 4,
  },
  {
    id: 12,
    name: "Whipped Oxygen Moisturizing Cream",
    image: "../../assets/ProductItems/whitedropper.jpg",
    price: 2999,
    stars: 5,
  },
  {
    id: 13,
    name: "Nivea Perfect and Radiant Body Cream",
    image: "../../assets/ProductItems/nivea.jpg",
    price: 9999,
    stars: 5,
  },
  {
    id: 14,
    name: "Loreal Shampooing - Silver",
    image: "../../assets/ProductItems/loreal.jpg",
    price: 6999,
    stars: 5,
  },
  {
    id: 15,
    name: "Dettol Skin protection Soap - 160g",
    image: "../../assets/ProductItems/dettol.jpg",
    price: 1599,
    stars: 5,
  },
  {
    id: 16,
    name: "Skin by Zaron Men - Face and Body Lotion",
    image: "../../assets/ProductItems/skinbyzaron.jpg",
    price: 4999,
    stars: 2,
  },
  {
    id: 17,
    name: "Skin by Zaron Men - Vitamin C Body Lotion",
    image: "../../assets/ProductItems/skinvitC.jpg",
    price: 8999,
    stars: 4,
  },
  {
    id: 18,
    name: "EAU DE PARFUM Body Natural Spray",
    image: "../../assets/ProductItems/perfume.jpg",
    price: 4999,
    stars: 5,
  },
  {
    id: 19,
    name: "CeraVe Acne Control Cleanser",
    image: "../../assets/ProductItems/cream.jpg",
    price: 7999,
    stars: 3,
  },
  {
    id: 20,
    name: "Venus Eye Pencil Collection 4-in-1 Pack",
    image: "../../assets/ProductItems/pencils.jpg",
    price: 3999,
    stars: 3,
  },
  {
    id: 21,
    name: "Rose Water Hydrating Mist",
    image: "../../assets/ProductItems/rosewater.jpg",
    price: 4999,
    stars: 4,
  },
  {
    id: 22,
    name: "Organic Coconut Oil Hair Mask",
    image: "../../assets/ProductItems/coconutoil.jpg",
    price: 7999,
    stars: 4,
  },
  {
    id: 23,
    name: "Aloe Vera Soothing Gel",
    image: "../../assets/ProductItems/aloevera.jpg",
    price: 3999,
    stars: 3,
  },
  {
    id: 24,
    name: "Tea Tree Oil Acne Treatment",
    image: "../../assets/ProductItems/teatreeoil.jpg",
    price: 5999,
    stars: 4,
  },
  {
    id: 25,
    name: "Ginseng Anti-Wrinkle Cream",
    image: "../../assets/ProductItems/ginsengcream.jpg",
    price: 8999,
    stars: 5,
  },
  {
    id: 26,
    name: "Charcoal Purifying Face Mask",
    image: "../../assets/ProductItems/charcoalmask.jpg",
    price: 4999,
    stars: 4,
  },
  {
    id: 27,
    name: "Hyaluronic Acid Serum",
    image: "../../assets/ProductItems/hyaluronicacid.jpg",
    price: 10999,
    stars: 5,
  },
  {
    id: 28,
    name: "Vitamin C Brightening Serum",
    image: "../../assets/ProductItems/vitamincserum.jpg",
    price: 7999,
    stars: 4,
  },
  {
    id: 29,
    name: "Argan Oil Hair Serum",
    image: "../../assets/ProductItems/arganoil.jpg",
    price: 5999,
    stars: 4,
  },
  {
    id: 30,
    name: "Jasmine Scented Bath Bombs",
    image: "../../assets/ProductItems/bathbombs.jpg",
    price: 2999,
    stars: 3,
  },
];
