export const Products = [
  {
    name: "Morocan Super Black Soap",
    image: "../../assets/ProductItems/crown.jpg",
    price: "N 7,520",
    stars: 4,
  },
  {
    name: "Venus Eye Lashes Collection 4-in-1 Pack",
    image: "../../assets/ProductItems/eyebrow.jpg",
    price: "N 4,999",
    stars: 4,
  },
  {
    name: "Foot Massage Syetem + Extra face",
    image: "../../assets/ProductItems/hairwasher.jpg",
    price: "N 5,999",
    stars: 3,
  },
  {
    name: "Whipped Oxygen Moisturizing Cream",
    image: "../../assets/ProductItems/whitedropper.jpg",
    price: "N 2,999",
    stars: 3,
  },
  {
    name: "Oxygen Plasma Liquids Drops",
    image: "../../assets/ProductItems/dropper.jpg",
    price: "N 7,880",
    stars: 4,
  },
  {
    name: "Balancing Stray Toner Cream",
    image: "../../assets/ProductItems/spraytoner.jpg",
    price: "N 5,999",
    stars: 4,
  },
  {
    name: "Allure Cream Conditioner + Shampoo",
    image: "../../assets/ProductItems/haircream.jpg",
    price: "N 4,999",
    stars: 5,
  },
  {
    name: "Manual hair remover + Extra tooth",
    image: "../../assets/ProductItems/shavingstick.jpg",
    price: "N 5,999",
    stars: 5,
  },
  {
    name: "Curl Expression Lotion Cream",
    image: "../../assets/ProductItems/curlcream.jpg",
    price: "N 4,999",
    stars: 5,
  },
  {
    name: "Collagen Super Powder",
    image: "../../assets/ProductItems/collagenpowder.jpg",
    price: "N 4,999",
    stars: 5,
  },
  {
    name: "Miracle Shampoo + Conditioner",
    image: "../../assets/ProductItems/miracleshampoo.jpg",
    price: "N 10,999",
    stars: 4,
  },
  {
    name: "Whipped Oxygen Moisturizing Cream",
    image: "../../assets/ProductItems/whitedropper.jpg",
    price: "N 2,999",
    stars: 5,
  },
  {
    name: "Nivea Perfect and Radiant Body Cream",
    image: "../../assets/ProductItems/nivea.jpg",
    price: "N 9,999",
    stars: 5,
  },
  {
    name: "Loreal Shampooing - Silver",
    image: "../../assets/ProductItems/loreal.jpg",
    price: "N 6,999",
    stars: 5,
  },
  {
    name: "Dettol Skin protection Soap - 160g",
    image: "../../assets/ProductItems/dettol.jpg",
    price: "N 1,599",
    stars: 5,
  },
  {
    name: "Skin by Zaron Men - Face and Body Lotion",
    image: "../../assets/ProductItems/skinbyzaron.jpg",
    price: "N 4,999",
    stars: 2,
  },
  {
    name: "Skin by Zaron Men - Vitamin C Body Lotion",
    image: "../../assets/ProductItems/skinvitC.jpg",
    price: "N 8,999",
    stars: 4,
  },
  {
    name: "EAU DE PARFUM Body Natural Spray",
    image: "../../assets/ProductItems/perfume.jpg",
    price: "N 4,999",
    stars: 5,
  },
  {
    name: "CeraVe Acne Control Cleanser",
    image: "../../assets/ProductItems/cream.jpg",
    price: "N 7,999",
    stars: 3,
  },
  {
    name: "Venus Eye Pencil Collection 4-in-1 Pack",
    image: "../../assets/ProductItems/pencils.jpg",
    price: "N 3,999",
    stars: 3,
  },
];
